name: Set up Gofumpt
description: Install Gofumpt formatter
branding:
  icon: package
  color: blue
runs:
  using: composite
  steps:
    - name: Install gofumpt
      shell: bash
      run: |
        wget https://github.com/mvdan/gofumpt/releases/download/v0.6.0/gofumpt_v0.6.0_linux_amd64
        mv gofumpt_v0.6.0_linux_amd64 gofumpt
        chmod +x gofumpt
        mv gofumpt /usr/local/bin
